import AppKit
import CryptoKit

/// One copied item's shareable representations. Rust validates everything
/// that crosses the session: kinds, UTF-8, format signatures and the 4 MiB total.
struct NativeClipboardContent: Equatable {
    var text: String?
    var rtf: Data?
    var png: Data?
    static let maxBytes = Int(ML_CLIPBOARD_MAX_BYTES)

    var isEmpty: Bool { text == nil && rtf == nil && png == nil }
    var byteCount: Int { (text?.utf8.count ?? 0) + (rtf?.count ?? 0) + (png?.count ?? 0) }
    /// For the log: which representations, never their contents.
    var summary: String {
        let kinds = [text.map { _ in "text" }, rtf.map { _ in "rich text" }, png.map { _ in "image" }].compactMap { $0 }
        return kinds.joined(separator: ", ") + " (\(ByteCountFormatter.string(fromByteCount: Int64(byteCount), countStyle: .file)))"
    }

    /// Keeps text, then the image, then rich text, within the size bound, and
    /// only representations Rust accepts. nil when nothing is left: text over
    /// the bound, or a MacLink pairing code, is not shared at all.
    func fitted() -> NativeClipboardContent? {
        if let text, NativePasteboard.containsPairingCode(text) { return nil }
        var result = NativeClipboardContent(text: text?.isEmpty == false ? text : nil)
        guard result.byteCount <= Self.maxBytes else { return nil }
        if let png, !png.isEmpty, result.byteCount + png.count <= Self.maxBytes, NativeClipboardContent(png: png).isValid { result.png = png }
        if let rtf, !rtf.isEmpty, result.byteCount + rtf.count <= Self.maxBytes, NativeClipboardContent(rtf: rtf).isValid { result.rtf = rtf }
        return result.isEmpty || !result.isValid ? nil : result
    }

    /// Calls `body` with the C items in ascending kind order; pointers are valid only inside it.
    func withItems<R>(_ body: (UnsafeBufferPointer<MLClipboardItem>) -> R) -> R {
        let parts: [(Int, Data)] = [(ML_CLIPBOARD_TEXT, text.map { Data($0.utf8) }), (ML_CLIPBOARD_RTF, rtf),
                                    (ML_CLIPBOARD_PNG, png)].compactMap { kind, data in data.map { (kind, $0) } }
        func nest(_ index: Int, _ items: [MLClipboardItem]) -> R {
            guard index < parts.count else { return items.withUnsafeBufferPointer(body) }
            return parts[index].1.withUnsafeBytes { bytes in
                var item = MLClipboardItem()
                item.bytes = bytes.bindMemory(to: UInt8.self).baseAddress; item.length = bytes.count
                item.kind = UInt8(parts[index].0)
                return nest(index + 1, items + [item])
            }
        }
        return nest(0, [])
    }
    var isValid: Bool { withItems { ml_clipboard_validate($0.baseAddress, $0.count) == ML_SESSION_OK } }
    /// The same copied item on either Mac: its text if any, else its image,
    /// else its rich text. Formats a round trip adds or drops do not change it.
    var identity: SHA256.Digest? {
        if let text { return SHA256.hash(data: Data(("text:" + text).utf8)) }
        if let png { return SHA256.hash(data: Data("png:".utf8) + png) }
        if let rtf { return SHA256.hash(data: Data("rtf:".utf8) + rtf) }
        return nil
    }
}

/// The pasteboard side of the shared clipboard.
enum NativePasteboard {
    /// Markers for passwords and other items that must never be shared or
    /// recorded: nspasteboard.org's, plus older password-manager conventions.
    static let privateTypes: Set<NSPasteboard.PasteboardType> = Set([
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword", "de.petermaurer.TransientPasteboardType", "Pasteboard generator type",
        "com.typeit4me.clipping", "net.antelle.keeweb"
    ].map { NSPasteboard.PasteboardType($0) })
    /// Universal Clipboard marks what it brought from another device. Both Macs
    /// signed in to the same Apple ID already share those items, and reading
    /// one here would fetch it over the network, so they are not sent.
    static let remoteClipboardType = NSPasteboard.PasteboardType("com.apple.is-remote-clipboard")
    /// Larger TIFF images are not converted; their PNG would exceed the bound anyway.
    static let maxTIFFBytes = 64 * 1024 * 1024
    /// MacLink's own pairing codes are secrets, even after an app drops their
    /// concealed marker on the way to the other Mac.
    static func containsPairingCode(_ text: String) -> Bool { text.contains("MLP1.") }
    /// macOS 15.4 and later may ask before an app reads the clipboard in the
    /// background; "always deny" means reading would fail anyway.
    static func readingDenied(_ pasteboard: NSPasteboard) -> Bool {
        if #available(macOS 15.4, *) { return pasteboard.accessBehavior == .alwaysDeny }
        return false
    }
    static func accessDescription(_ pasteboard: NSPasteboard) -> String {
        guard #available(macOS 15.4, *) else { return "not applicable" }
        switch pasteboard.accessBehavior {
        case .alwaysAllow: return "always allow"
        case .alwaysDeny: return "always deny"
        case .ask: return "ask"
        default: return "default"
        }
    }

    /// What this pasteboard can share now, plus a TIFF image still to convert;
    /// nil when it is empty or marked private.
    static func read(_ pasteboard: NSPasteboard) -> (content: NativeClipboardContent, tiff: Data?)? {
        let types = Set(pasteboard.types ?? [])
        guard !types.isEmpty, types.isDisjoint(with: privateTypes), !types.contains(remoteClipboardType) else { return nil }
        var content = NativeClipboardContent()
        content.text = pasteboard.string(forType: .string)
        if let text = content.text, containsPairingCode(text) { return nil }
        content.rtf = pasteboard.data(forType: .rtf)
        // Copied files share their names as text only, not Finder's icon image.
        guard !types.contains(.fileURL) else { content.rtf = nil; return content.text == nil ? nil : (content, nil) }
        content.png = pasteboard.data(forType: .png)
        var tiff: Data?
        if content.png == nil, let image = pasteboard.data(forType: .tiff), image.count <= maxTIFFBytes { tiff = image }
        return content.isEmpty && tiff == nil ? nil : (content, tiff)
    }
    static func png(fromTIFF tiff: Data) -> Data? {
        NSBitmapImageRep(data: tiff)?.representation(using: .png, properties: [:])
    }
    static func write(_ content: NativeClipboardContent, to pasteboard: NSPasteboard) {
        let item = NSPasteboardItem()
        if let text = content.text { item.setString(text, forType: .string) }
        if let rtf = content.rtf { item.setData(rtf, forType: .rtf) }
        if let png = content.png { item.setData(png, forType: .png) }
        pasteboard.clearContents(); pasteboard.writeObjects([item])
    }
}

/// Follows this Mac's clipboard while a session is connected. Every pasteboard
/// access runs on one serial utility queue: data another app or Universal
/// Clipboard provides lazily can take seconds to read, and must never stall
/// the main thread, which draws the picture and answers connection checks.
/// Nothing matching the item last exchanged in either direction is sent, so no
/// echo path (Universal Clipboard, clipboard managers) can bounce it back.
final class NativeClipboardSync: @unchecked Sendable {
    /// Called on the main thread.
    var onSend: ((NativeClipboardContent) -> Void)?
    private let pasteboard: NSPasteboard
    private let queue = DispatchQueue(label: "dev.maclink.clipboard", qos: .utility)
    private let pollLock = NSLock()
    private var pollQueued = false
    // Confined to `queue`.
    private var seenChangeCount: Int?
    private var exchangedChangeCount: Int?
    private var exchanged: SHA256.Digest?

    init(pasteboard: NSPasteboard = .general) { self.pasteboard = pasteboard }
    /// Follows changes from now on; `includeCurrent` also shares what is copied
    /// already, unless it is what was last exchanged.
    func start(includeCurrent: Bool) {
        queue.async { [self] in
            let count = pasteboard.changeCount
            seenChangeCount = count
            if includeCurrent && count != exchangedChangeCount && !NativePasteboard.readingDenied(pasteboard) { publish(count) }
        }
    }
    /// Main thread, twice a second. At most one poll waits behind a slow read.
    func poll() {
        pollLock.lock()
        guard !pollQueued else { pollLock.unlock(); return }
        pollQueued = true; pollLock.unlock()
        queue.async { [self] in
            pollLock.lock(); pollQueued = false; pollLock.unlock()
            guard !NativePasteboard.readingDenied(pasteboard) else { return }
            let count = pasteboard.changeCount
            guard count != seenChangeCount else { return }
            seenChangeCount = count
            publish(count)
        }
    }
    /// Writes the other Mac's copy here; it is never sent back.
    func apply(_ content: NativeClipboardContent) {
        queue.async { [self] in
            NativePasteboard.write(content, to: pasteboard)
            let count = pasteboard.changeCount
            seenChangeCount = count; exchangedChangeCount = count; exchanged = content.identity
        }
    }
    /// Waits for queued pasteboard work; for tests.
    func waitUntilIdle() { queue.sync {} }

    private func publish(_ count: Int) {
        guard let read = NativePasteboard.read(pasteboard) else { return }
        var content = read.content
        if let tiff = read.tiff { content.png = NativePasteboard.png(fromTIFF: tiff) }
        // A newer copy supersedes this one; the next poll reads it.
        guard pasteboard.changeCount == count, let fitted = content.fitted() else { return }
        exchangedChangeCount = count
        let identity = fitted.identity
        guard identity != exchanged else { return }
        exchanged = identity
        DispatchQueue.main.async { [weak self] in self?.onSend?(fitted) }
    }
}
