import AppKit

/// One copied item's shareable representations. Rust validates everything
/// that crosses the session: kinds, UTF-8, format signatures and the 4 MiB total.
struct NativeClipboardContent: Equatable {
    var text: String?
    var rtf: Data?
    var png: Data?
    static let maxBytes = Int(ML_CLIPBOARD_MAX_BYTES)

    var isEmpty: Bool { text == nil && rtf == nil && png == nil }
    var byteCount: Int { (text?.utf8.count ?? 0) + (rtf?.count ?? 0) + (png?.count ?? 0) }
    /// For the log: which representations, never their contents.
    var summary: String {
        let kinds = [text.map { _ in "text" }, rtf.map { _ in "rich text" }, png.map { _ in "image" }].compactMap { $0 }
        return kinds.joined(separator: ", ") + " (\(ByteCountFormatter.string(fromByteCount: Int64(byteCount), countStyle: .file)))"
    }

    /// Keeps text, then the image, then rich text, within the size bound, and
    /// only representations Rust accepts. nil when nothing is left: text over
    /// the bound, or a MacLink pairing code, is not shared at all.
    func fitted() -> NativeClipboardContent? {
        if let text, NativePasteboard.containsPairingCode(text) { return nil }
        var result = NativeClipboardContent(text: text?.isEmpty == false ? text : nil)
        guard result.byteCount <= Self.maxBytes else { return nil }
        if let png, !png.isEmpty, result.byteCount + png.count <= Self.maxBytes, NativeClipboardContent(png: png).isValid { result.png = png }
        if let rtf, !rtf.isEmpty, result.byteCount + rtf.count <= Self.maxBytes, NativeClipboardContent(rtf: rtf).isValid { result.rtf = rtf }
        return result.isEmpty || !result.isValid ? nil : result
    }

    /// Calls `body` with the C items in ascending kind order; pointers are valid only inside it.
    func withItems<R>(_ body: (UnsafeBufferPointer<MLClipboardItem>) -> R) -> R {
        let parts: [(Int, Data)] = [(ML_CLIPBOARD_TEXT, text.map { Data($0.utf8) }), (ML_CLIPBOARD_RTF, rtf),
                                    (ML_CLIPBOARD_PNG, png)].compactMap { kind, data in data.map { (kind, $0) } }
        func nest(_ index: Int, _ items: [MLClipboardItem]) -> R {
            guard index < parts.count else { return items.withUnsafeBufferPointer(body) }
            return parts[index].1.withUnsafeBytes { bytes in
                var item = MLClipboardItem()
                item.bytes = bytes.bindMemory(to: UInt8.self).baseAddress; item.length = bytes.count
                item.kind = UInt8(parts[index].0)
                return nest(index + 1, items + [item])
            }
        }
        return nest(0, [])
    }
    var isValid: Bool { withItems { ml_clipboard_validate($0.baseAddress, $0.count) == ML_SESSION_OK } }
}

/// The pasteboard side of the shared clipboard.
enum NativePasteboard {
    /// Markers for passwords and other items that must never be shared or
    /// recorded: nspasteboard.org's, plus older password-manager conventions.
    static let privateTypes: Set<NSPasteboard.PasteboardType> = Set([
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword", "de.petermaurer.TransientPasteboardType", "Pasteboard generator type",
        "com.typeit4me.clipping", "net.antelle.keeweb"
    ].map { NSPasteboard.PasteboardType($0) })
    /// Larger TIFF images are not converted; their PNG would exceed the bound anyway.
    static let maxTIFFBytes = 64 * 1024 * 1024
    /// MacLink's own pairing codes are secrets, even after an app drops their
    /// concealed marker on the way to the other Mac.
    static func containsPairingCode(_ text: String) -> Bool { text.contains("MLP1.") }
    /// macOS 15.4 and later may ask before an app reads the clipboard in the
    /// background; "always deny" means reading would fail anyway.
    static func readingDenied(_ pasteboard: NSPasteboard) -> Bool {
        if #available(macOS 15.4, *) { return pasteboard.accessBehavior == .alwaysDeny }
        return false
    }
    static func accessDescription(_ pasteboard: NSPasteboard) -> String {
        guard #available(macOS 15.4, *) else { return "not applicable" }
        switch pasteboard.accessBehavior {
        case .alwaysAllow: return "always allow"
        case .alwaysDeny: return "always deny"
        case .ask: return "ask"
        default: return "default"
        }
    }

    /// What this pasteboard can share now, plus a TIFF image still to convert;
    /// nil when it is empty or marked private.
    static func read(_ pasteboard: NSPasteboard) -> (content: NativeClipboardContent, tiff: Data?)? {
        let types = Set(pasteboard.types ?? [])
        guard !types.isEmpty, types.isDisjoint(with: privateTypes) else { return nil }
        var content = NativeClipboardContent()
        content.text = pasteboard.string(forType: .string)
        if let text = content.text, containsPairingCode(text) { return nil }
        content.rtf = pasteboard.data(forType: .rtf)
        // Copied files share their names as text only, not Finder's icon image.
        guard !types.contains(.fileURL) else { content.rtf = nil; return content.text == nil ? nil : (content, nil) }
        content.png = pasteboard.data(forType: .png)
        var tiff: Data?
        if content.png == nil, let image = pasteboard.data(forType: .tiff), image.count <= maxTIFFBytes { tiff = image }
        return content.isEmpty && tiff == nil ? nil : (content, tiff)
    }
    static func png(fromTIFF tiff: Data) -> Data? {
        NSBitmapImageRep(data: tiff)?.representation(using: .png, properties: [:])
    }
    static func write(_ content: NativeClipboardContent, to pasteboard: NSPasteboard) {
        let item = NSPasteboardItem()
        if let text = content.text { item.setString(text, forType: .string) }
        if let rtf = content.rtf { item.setData(rtf, forType: .rtf) }
        if let png = content.png { item.setData(png, forType: .png) }
        pasteboard.clearContents(); pasteboard.writeObjects([item])
    }
}

/// Follows this Mac's clipboard while a session is connected. The change count
/// is polled on the main thread; TIFF images convert to PNG off it. Content
/// applied from the other Mac is never echoed back.
final class NativeClipboardSync {
    var onSend: ((NativeClipboardContent) -> Void)?
    private let pasteboard: NSPasteboard
    private var seenChangeCount: Int
    /// The last change sent or applied; a reconnect does not resend it.
    private var exchangedChangeCount: Int?
    private var generation: UInt64 = 0
    private let converter = DispatchQueue(label: "dev.maclink.clipboard", qos: .utility)
    /// One image conversion at a time; a newer copy waits for it, then re-reads.
    private var converting = false
    private var rereadGeneration: UInt64?

    init(pasteboard: NSPasteboard = .general) {
        self.pasteboard = pasteboard; seenChangeCount = pasteboard.changeCount
    }
    /// Follows changes from now on; `includeCurrent` also shares what is copied
    /// already, unless it is what was last exchanged.
    func start(includeCurrent: Bool) {
        generation &+= 1; seenChangeCount = pasteboard.changeCount
        if includeCurrent && seenChangeCount != exchangedChangeCount && !NativePasteboard.readingDenied(pasteboard) { publish() }
    }
    /// Main thread; cheap when nothing changed.
    func poll() {
        guard !NativePasteboard.readingDenied(pasteboard) else { return }
        let count = pasteboard.changeCount
        guard count != seenChangeCount else { return }
        seenChangeCount = count
        publish()
    }
    func apply(_ content: NativeClipboardContent) {
        NativePasteboard.write(content, to: pasteboard)
        generation &+= 1; seenChangeCount = pasteboard.changeCount; exchangedChangeCount = seenChangeCount
    }
    private func publish() {
        guard let read = NativePasteboard.read(pasteboard) else { return }
        let count = seenChangeCount
        guard let tiff = read.tiff else {
            if let content = read.content.fitted() { exchangedChangeCount = count; onSend?(content) }
            return
        }
        guard !converting else { rereadGeneration = generation; return }
        converting = true
        let token = generation
        converter.async { [weak self] in
            let png = NativePasteboard.png(fromTIFF: tiff)
            DispatchQueue.main.async {
                guard let self else { return }
                self.converting = false
                // A newer copy, or content from the other Mac, supersedes this one.
                if self.generation == token, self.seenChangeCount == count {
                    var content = read.content; content.png = png
                    if let fitted = content.fitted() { self.exchangedChangeCount = count; self.onSend?(fitted) }
                }
                if let reread = self.rereadGeneration {
                    self.rereadGeneration = nil
                    if reread == self.generation { self.publish() }
                }
            }
        }
    }
}
